---
- name: Create VM from Vcenter Template
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Clone Template to New Virtual Machine
      community.vmware.vmware_guest:
        validate_certs: false
        name: "{{ vm_name }}"
        template: plantilla_helper
        datacenter: DCUIO
        resource_pool: # Input Resource Pool
        folder: "/DCUIO/vm/AWX"
        state: poweredon
        wait_for_ip_address: true
        networks:
          - name: "{{ vm_net_namelan }}"
            ip: "{{ vm_iplan }}"
            netmask: "{{ vm_net_mask_lan }}"
            gateway: "{{ vm_net_gw }}"
          - name: "{{ vm_net_namesan }}"
            ip: "{{ vm_ipsan }}"
            netmask: "{{ vm_net_mask_san }}"
        customization:
          dns_servers:
          - "{{ vm_net_dns }}"

