---
- name: Create VM from Vcenter Template
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Clone Template to New Virtual Machine
      community.vmware.vmware_guest:
        validate_certs: false
        name: "{{ vm_name }}"
        template: plantilla_helper
        datacenter: DCUIO
        resource_pool: # Input Resource Pool
        folder: "/DCUIO/vm/AWX"
        state: poweredon
        wait_for_ip_address: true
        networks:
          - name: "{{ vm_net_namelan }}"
            ip: "{{ vm_iplan }}"
            netmask: "{{ vm_net_mask }}"
            gateway: "{{ vm_net_gw }}"
            dns_servers: "{{ vm_net_dns }}"
          - name: "{{ vm_net_namesan }}"
            ip: "{{ vm_ipsan }}"
            netmask: "{{ vm_net_mask }}"
    - name: Pause for 120 seconds to wait for reboot
      ansible.builtin.pause:
        seconds: "120"

- name: Set VM IP and Hostname
  hosts: 172.30.210.160 # This is the IP that is set for the template, if you use a different IP update here.
  become: true
  tasks:

    - name: Update Hostname
      
      ansible.builtin.hostname:
        name: "{{ hostname }}" # Update domain
        
    - name: Update IP
      ansible.builtin.lineinfile:
        path: /etc/netplan/00-installer-config.yaml
        regex: "- 172.30.210.160/23" # Set to same IP as line 19
        line: "        - {{ new_IP }}/23"
        
    - name: Reboot
      ansible.builtin.command: "init 6"
      ignore_errors: true

    - name: Pause for 30 seconds to wait for reboot
      ansible.builtin.pause:
        seconds: "10"
        
