---
- name: Create VM from Vcenter Template
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Clone Template to New Virtual Machine
      community.vmware.vmware_guest:
        validate_certs: false
        name: "{{ vm_name }}"
        template: plantilla_helper
        datacenter: DCUIO
        resource_pool: # Input Resource Pool
        folder: "/DCUIO/vm/AWX"
        state: poweredon
        wait_for_ip_address: true
    - name: Pause for 120 seconds to wait for reboot
      ansible.builtin.pause:
        seconds: "120"

- name: Set VM IP and Hostname
  hosts: 172.30.210.160 # This is the IP that is set for the template, if you use a different IP update here.
  become: true
  tasks:

    - name: Update Hostname
      
      ansible.builtin.hostname:
        name: "{{ hostname }}" # Update domain
        
    - name: Update IP escucha
      ansible.builtin.lineinfile:
        path: /etc/bind9/named.conf.options
        regex: "10.10.5.73" # Set to same IP as line 19
        line: "{{ new_IP }}"
        
    - name: Update red origen
      ansible.builtin.lineinfile:
        path: /etc/bind9/named.conf.options
        regex: "10.10.5.64/28" # Set to same IP as line 19
        line: "{{ new_IP }}/{{ new_prefix }}"
        
    - name: Reboot
      ansible.builtin.command: "init 6"
      ignore_errors: true

    - name: Pause for 30 seconds to wait for reboot
      ansible.builtin.pause:
        seconds: "10"
        
