---
- name: Create VM from Vcenter Template
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Clone Template to New Virtual Machine
      community.vmware.vmware_guest:
        validate_certs: false
        name: "{{ vm_name }}"
        template: plantilla_helper
        datacenter: DCUIO
        resource_pool: # Input Resource Pool
        folder: "/DCUIO/vm/AWX"
        state: poweredon
        wait_for_ip_address: true

- name: Set VM IP and Hostname
  hosts: 10.10.5.73/28 # This is the IP that is set for the template, if you use a different IP update here.
  tasks:
    - name: Update IP
      ansible.builtin.lineinfile:
        path: /etc/netplan/00-installer-config.yaml
        regex: "addresses=10.10.5.73/28" # Set to same IP as line 19
        line: "addresses={{ new_IP }}"

    - name: Update Hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}.domain.local" # Update domain

    - name: Reboot
      ansible.builtin.command: "init 6"
      ignore_errors: true

    - name: Pause for 30 seconds to wait for reboot
      ansible.builtin.pause:
        seconds: "10"
